"""trip service_id satırını nullable=False yapıldı

Revision ID: 593ea14262fc
Revises: 6a201ac8d377
Create Date: 2026-08-05 15:03:49.895624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593ea14262fc'
down_revision: Union[str, Sequence[str], None] = '6a201ac8d377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'service_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'service_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
