"""add celery_task_id to import_gtfs

Revision ID: 8740359bbce2
Revises: e63d27d3e053
Create Date: 2026-08-13 12:58:10.414050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8740359bbce2'
down_revision: Union[str, Sequence[str], None] = 'e63d27d3e053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_gtfs', sa.Column('celery_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_gtfs', 'celery_task_id')
    # ### end Alembic commands ###
