"""add file_checksum to import_gtfs

Revision ID: e63d27d3e053
Revises: e6cd074a6cc0
Create Date: 2026-08-11 14:12:38.696481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63d27d3e053'
down_revision: Union[str, Sequence[str], None] = 'e6cd074a6cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_gtfs', sa.Column('file_checksum', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_gtfs', 'file_checksum')
    # ### end Alembic commands ###
