"""Stop tablosunda stopl_lon düzeltildi

Revision ID: e6cd074a6cc0
Revises: 593ea14262fc
Create Date: 2026-08-06 11:26:18.559316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cd074a6cc0'
down_revision: Union[str, Sequence[str], None] = '593ea14262fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stops', sa.Column('stop_lon', sa.Float(), nullable=True))
    op.drop_column('stops', 'stopl_lon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stops', sa.Column('stopl_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('stops', 'stop_lon')
    # ### end Alembic commands ###
